### ISSUE TITLE
URL not displaying correctly

### ISSUE THREAD

**Issue by californiasteve** [bmlt-enabled/contacts-bmlt#1]
When the url is entered into the BMLT database without the https:// at the beginning the url is appended to the websites url. Example hillcountyna.org becomes https://californiasteve.com/wptest/contacts/hillcountryna.org

**Comment by pjaudiomv** [comment]
so this is how hypelinks work, any hyperlink in an anchor tag that doesnt have http is going to think that the link is relative to current url. I would suggest adding http to the urls. If I can come up with a way to check and add them properly I will but it would be tough to do because I would have no way to know if it should be http or https

**Comment by pjaudiomv** [comment]
ok cool I think I found a reliable way to check for this.

**Comment by pjaudiomv** [comment]
this should fix it https://github.com/bmlt-enabled/contacts-bmlt/releases/download/1.0.0-beta1/contacts-bmlt.zip
